[project]
name = "youtubedownload"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "static-ffmpeg>=2.13",
    "yt-dlp>=2025.6.9",
]
